package fr.gstraymond.scrap.card.constants

class Title {

	static MAP = [
		'AErathi Berserker'		: '\u00C6rathi Berserker',
		'AEther Adept'			: '\u00C6ther Adept',
		'AEther Barrier'		: '\u00C6ther Barrier',
		'AEther Burst'			: '\u00C6ther Burst',
		'AEther Charge'			: '\u00C6ther Charge',
		'AEther Figment'		: '\u00C6ther Figment',
		'AEther Flash'			: '\u00C6ther Flash',
		'AEther Membrane'		: '\u00C6ther Membrane',
		'AEther Mutation'		: '\u00C6ther Mutation',
		'AEther Rift'			: '\u00C6ther Rift',
		'AEther Shockwave'		: '\u00C6ther Shockwave',
		'AEther Snap'			: '\u00C6ther Snap',
		'AEther Spellbomb'		: '\u00C6ther Spellbomb',
		'AEther Sting'			: '\u00C6ther Sting',
		'AEther Storm'			: '\u00C6ther Storm',
		'AEther Tide'			: '\u00C6ther Tide',
		'AEther Tradewinds'		: '\u00C6ther Tradewinds',
		'AEther Vial'			: '\u00C6ther Vial',
		'AEther Web'			: '\u00C6ther Web',
		'AEtherflame Wall'		: '\u00C6therflame Wall',
		'AEtherize'				: '\u00C6therize',
		'AEtherling'			: '\u00C6therling',
		'AEthermage\'s Touch'	: '\u00C6thermage\'s Touch',
		'AEtherplasm'			: '\u00C6therplasm',
		'AEthersnipe'			: '\u00C6thersnipe',
		'AEthertow'				: '\u00C6thertow',
		'Arm with AEther'		: 'Arm with \u00C6ther',
		'Azorius AEthermage'	: 'Azorius \u00C6thermage',
		'Bosium Strip'			: 'B\u00F6sium Strip',
		'Dandan'				: 'Dand\u00E2n',
		'Deja Vu'				: 'D\u00E9j\u00E0 Vu',
		'El-Hajjaj'				: 'El-Hajj\u00E2j',
		'Fold into AEther'		: 'Fold into \u00C6ther',
		'Frozen AEther'			: 'Frozen \u00C6ther',
		'Gate to the AEther'	: 'Gate to the \u00C6ther',
		'Ghazban Ogre'			: 'Ghazb\u00E1n Ogre',
		'Ifh-Biff Efreet'		: 'Ifh-B\u00EDff Efreet',
		'Jotun Grunt'			: 'J\u00F6tun Grunt',
		'Jotun Owl Keeper'		: 'J\u00F6tun Owl Keeper',
		'Junun Efreet'			: 'Jun\u00FAn Efreet',
		'Juzam Djinn'			: 'Juz\u00E1m Djinn',
		'Khabal Ghoul'			: 'Khab\u00E1l Ghoul',
		'Kongming, "Sleeping Dragon"'	: 'Kongming, \u201CSleeping Dragon\u201D',
		'Legions of Lim-Dul'	: 'Legions of Lim-D\u00FBl',
		'Lim-Dul the Necromancer' : 'Lim-D\u00FBl the Necromancer',
		'Lim-Dul\'s Cohort'		: 'Lim-D\u00FBl\'s Cohort',
		'Lim-Dul\'s Hex'		: 'Lim-D\u00FBl\'s Hex',
		'Lim-Dul\'s Paladin'	: 'Lim-D\u00FBl\'s Paladin',
		'Lim-Dul\'s Vault'		: 'Lim-D\u00FBl\'s Vault',
		'Marton Stromgald'		: 'M\u00E1rton Stromgald',
		'Oath of Lim-Dul'		: 'Oath of Lim-D\u00FBl',
		'Pang Tong, "Young Phoenix"'	: 'Pang Tong, \u201CYoung Phoenix\u201D',
		'Ring of Ma\'ruf'		: 'Ring of Ma\'r\u00FBf',
		'Scornful AEther-Lich'	: 'Scornful \u00C6ther-Lich',
		'Seance'				: 'S\u00E9ance',
		'Surging AEther'		: 'Surging \u00C6ther',
		'Tainted AEther'		: 'Tainted \u00C6ther',
		'Vedalken AEthermage'	: 'Vedalken \u00C6thermage'
	]
}
